
[[constraint]]
  name = "github.com/gobwas/glob"
  version = "0.2.3"

[[constraint]]
  name = "github.com/google/go-cmp"
  version = "0.2.0"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.6.2"

[[constraint]]
  name = "github.com/influxdata/go-syslog"
  version = "2.0.0"

[[constraint]]
  name = "github.com/influxdata/tail"
  branch = "master"

[[constraint]]
  name = "github.com/influxdata/toml"
  branch = "master"

[[constraint]]
  name = "github.com/influxdata/wlog"
  branch = "master"

[[constraint]]
  name = "github.com/kardianos/service"
  branch = "master"

[[constraint]]
  name = "github.com/kballard/go-shellquote"
  branch = "master"

[[constraint]]
  name = "github.com/miekg/dns"
  version = "1.0.8"

[[constraint]]
  name = "github.com/nats-io/gnatsd"
  version = "1.1.0"

[[constraint]]
  name = "github.com/nats-io/go-nats"
  version = "1.5.0"

[[constraint]]
  name = "github.com/satori/go.uuid"
  version = "1.2.0"

[[constraint]]
  name = "github.com/shirou/gopsutil"
  version = "2.18.07"

[[constraint]]
  name = "github.com/Shopify/sarama"
  version = "1.18.0"

[[constraint]]
  name = "github.com/soniah/gosnmp"
  branch = "master"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.2"

[[constraint]]
  name = "github.com/tidwall/gjson"
  version = "1.1.1"

[[constraint]]
  name = "github.com/vjeantet/grok"
  version = "1.0.0"

[[constraint]]
  name = "golang.org/x/sys"
  branch = "master"

[[override]]
  name = "github.com/vishvananda/netlink"
  revision = "b2de5d10e38ecce8607e6b438b6d174f389a004e"

[[constraint]]
  name = "github.com/karrick/godirwalk"
  version = "1.7.5"

