package all

import (
	_ "github.com/lavaorg/telex/plugins/inputs/bcache"
	_ "github.com/lavaorg/telex/plugins/inputs/cgroup"
	_ "github.com/lavaorg/telex/plugins/inputs/conntrack"
	_ "github.com/lavaorg/telex/plugins/inputs/cpu"
	_ "github.com/lavaorg/telex/plugins/inputs/disk"
	_ "github.com/lavaorg/telex/plugins/inputs/diskio"
	_ "github.com/lavaorg/telex/plugins/inputs/dmcache"
	_ "github.com/lavaorg/telex/plugins/inputs/dns_query"
	_ "github.com/lavaorg/telex/plugins/inputs/exec"
	_ "github.com/lavaorg/telex/plugins/inputs/file"
	_ "github.com/lavaorg/telex/plugins/inputs/filecount"
	_ "github.com/lavaorg/telex/plugins/inputs/filestat"
	_ "github.com/lavaorg/telex/plugins/inputs/hddtemp"
//	_ "github.com/lavaorg/telex/plugins/inputs/http"
//	_ "github.com/lavaorg/telex/plugins/inputs/http_listener_v2"
//	_ "github.com/lavaorg/telex/plugins/inputs/http_response"
//	_ "github.com/lavaorg/telex/plugins/inputs/httpjson"
	_ "github.com/lavaorg/telex/plugins/inputs/internal"
	_ "github.com/lavaorg/telex/plugins/inputs/interrupts"
	_ "github.com/lavaorg/telex/plugins/inputs/ipmi_sensor"
	_ "github.com/lavaorg/telex/plugins/inputs/ipset"
	_ "github.com/lavaorg/telex/plugins/inputs/iptables"
	_ "github.com/lavaorg/telex/plugins/inputs/ipvs"
	_ "github.com/lavaorg/telex/plugins/inputs/kernel"
	_ "github.com/lavaorg/telex/plugins/inputs/kernel_vmstat"
	_ "github.com/lavaorg/telex/plugins/inputs/linux_sysctl_fs"
	_ "github.com/lavaorg/telex/plugins/inputs/logparser"
	_ "github.com/lavaorg/telex/plugins/inputs/mem"
//	_ "github.com/lavaorg/telex/plugins/inputs/nats"
//	_ "github.com/lavaorg/telex/plugins/inputs/nats_consumer"
	_ "github.com/lavaorg/telex/plugins/inputs/net"
	_ "github.com/lavaorg/telex/plugins/inputs/net_response"
	_ "github.com/lavaorg/telex/plugins/inputs/nstat"
	_ "github.com/lavaorg/telex/plugins/inputs/ping"
	_ "github.com/lavaorg/telex/plugins/inputs/processes"
	_ "github.com/lavaorg/telex/plugins/inputs/procstat"
	_ "github.com/lavaorg/telex/plugins/inputs/sensors"
	_ "github.com/lavaorg/telex/plugins/inputs/smart"
	_ "github.com/lavaorg/telex/plugins/inputs/snmp"
	_ "github.com/lavaorg/telex/plugins/inputs/socket_listener"
	_ "github.com/lavaorg/telex/plugins/inputs/swap"
	_ "github.com/lavaorg/telex/plugins/inputs/syslog"
	_ "github.com/lavaorg/telex/plugins/inputs/sysstat"
	_ "github.com/lavaorg/telex/plugins/inputs/system"
	_ "github.com/lavaorg/telex/plugins/inputs/tail"
	_ "github.com/lavaorg/telex/plugins/inputs/tcp_listener"
	_ "github.com/lavaorg/telex/plugins/inputs/temp"
	_ "github.com/lavaorg/telex/plugins/inputs/trig"
	_ "github.com/lavaorg/telex/plugins/inputs/udp_listener"
//	_ "github.com/lavaorg/telex/plugins/inputs/unbound"
//	_ "github.com/lavaorg/telex/plugins/inputs/webhooks"
	_ "github.com/lavaorg/telex/plugins/inputs/x509_cert"
//	_ "github.com/lavaorg/telex/plugins/inputs/zfs"
)
